using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ProjetoEventX.Migrations
{
    public partial class AddEventXSocialStoriesAndSavedPosts : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                ALTER TABLE "SocialPosts" ADD COLUMN IF NOT EXISTS "TipoConteudo" character varying(80);
                ALTER TABLE "SocialPosts" ADD COLUMN IF NOT EXISTS "Localizacao" character varying(140);
                ALTER TABLE "SocialComentarios" ADD COLUMN IF NOT EXISTS "PerfilSocialId" integer;
                """);

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "SocialPostsSalvos" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "PostId" integer NOT NULL,
                    "UserId" integer NOT NULL,
                    "CriadoEm" timestamp with time zone NOT NULL
                );
                """);

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "SocialStatus" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "UserId" integer NOT NULL,
                    "PerfilSocialId" integer NOT NULL,
                    "ImagemUrl" character varying(300) NOT NULL,
                    "TextoOverlay" character varying(180),
                    "CriadoEm" timestamp with time zone NOT NULL,
                    "ExpiraEm" timestamp with time zone NOT NULL,
                    "Ativo" boolean NOT NULL
                );
                """);

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "SocialStatusVisualizacoes" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "SocialStatusId" integer NOT NULL,
                    "UserId" integer NOT NULL,
                    "VisualizadoEm" timestamp with time zone NOT NULL
                );
                """);

            migrationBuilder.Sql("""
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1
                        FROM information_schema.columns
                        WHERE table_name = 'SocialStatusVisualizacoes'
                          AND column_name = 'StatusId'
                    ) AND NOT EXISTS (
                        SELECT 1
                        FROM information_schema.columns
                        WHERE table_name = 'SocialStatusVisualizacoes'
                          AND column_name = 'SocialStatusId'
                    ) THEN
                        ALTER TABLE "SocialStatusVisualizacoes" RENAME COLUMN "StatusId" TO "SocialStatusId";
                    END IF;

                    IF NOT EXISTS (
                        SELECT 1
                        FROM information_schema.columns
                        WHERE table_name = 'SocialStatusVisualizacoes'
                          AND column_name = 'SocialStatusId'
                    ) THEN
                        ALTER TABLE "SocialStatusVisualizacoes" ADD COLUMN "SocialStatusId" integer;
                    END IF;
                END $$;
                """);

            migrationBuilder.Sql("""
                ALTER TABLE "SocialComentarios"
                DROP CONSTRAINT IF EXISTS "FK_SocialComentarios_PerfisSociais_PerfilSocialId";
                ALTER TABLE "SocialComentarios"
                ADD CONSTRAINT "FK_SocialComentarios_PerfisSociais_PerfilSocialId"
                FOREIGN KEY ("PerfilSocialId") REFERENCES "PerfisSociais" ("Id") ON DELETE SET NULL;
                """);

            migrationBuilder.Sql("""
                ALTER TABLE "SocialPostsSalvos"
                DROP CONSTRAINT IF EXISTS "FK_SocialPostsSalvos_AspNetUsers_UserId";
                ALTER TABLE "SocialPostsSalvos"
                ADD CONSTRAINT "FK_SocialPostsSalvos_AspNetUsers_UserId"
                FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT;

                ALTER TABLE "SocialPostsSalvos"
                DROP CONSTRAINT IF EXISTS "FK_SocialPostsSalvos_SocialPosts_PostId";
                ALTER TABLE "SocialPostsSalvos"
                ADD CONSTRAINT "FK_SocialPostsSalvos_SocialPosts_PostId"
                FOREIGN KEY ("PostId") REFERENCES "SocialPosts" ("Id") ON DELETE CASCADE;
                """);

            migrationBuilder.Sql("""
                ALTER TABLE "SocialStatus"
                DROP CONSTRAINT IF EXISTS "FK_SocialStatus_AspNetUsers_UserId";
                ALTER TABLE "SocialStatus"
                ADD CONSTRAINT "FK_SocialStatus_AspNetUsers_UserId"
                FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT;

                ALTER TABLE "SocialStatus"
                DROP CONSTRAINT IF EXISTS "FK_SocialStatus_PerfisSociais_PerfilSocialId";
                ALTER TABLE "SocialStatus"
                ADD CONSTRAINT "FK_SocialStatus_PerfisSociais_PerfilSocialId"
                FOREIGN KEY ("PerfilSocialId") REFERENCES "PerfisSociais" ("Id") ON DELETE CASCADE;
                """);

            migrationBuilder.Sql("""
                ALTER TABLE "SocialStatusVisualizacoes"
                DROP CONSTRAINT IF EXISTS "FK_SocialStatusVisualizacoes_AspNetUsers_UserId";
                ALTER TABLE "SocialStatusVisualizacoes"
                ADD CONSTRAINT "FK_SocialStatusVisualizacoes_AspNetUsers_UserId"
                FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT;

                ALTER TABLE "SocialStatusVisualizacoes"
                DROP CONSTRAINT IF EXISTS "FK_SocialStatusVisualizacoes_SocialStatus_SocialStatusId";
                ALTER TABLE "SocialStatusVisualizacoes"
                ADD CONSTRAINT "FK_SocialStatusVisualizacoes_SocialStatus_SocialStatusId"
                FOREIGN KEY ("SocialStatusId") REFERENCES "SocialStatus" ("Id") ON DELETE CASCADE;
                """);

            migrationBuilder.Sql("""
                CREATE INDEX IF NOT EXISTS "IX_SocialComentarios_PerfilSocialId" ON "SocialComentarios" ("PerfilSocialId");
                CREATE INDEX IF NOT EXISTS "IX_SocialPostsSalvos_UserId" ON "SocialPostsSalvos" ("UserId");
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_SocialPostsSalvos_PostId_UserId" ON "SocialPostsSalvos" ("PostId", "UserId");
                CREATE INDEX IF NOT EXISTS "IX_SocialStatus_UserId" ON "SocialStatus" ("UserId");
                CREATE INDEX IF NOT EXISTS "IX_SocialStatus_PerfilSocialId_ExpiraEm_Ativo" ON "SocialStatus" ("PerfilSocialId", "ExpiraEm", "Ativo");
                CREATE INDEX IF NOT EXISTS "IX_SocialStatusVisualizacoes_UserId" ON "SocialStatusVisualizacoes" ("UserId");
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_SocialStatusVisualizacoes_SocialStatusId_UserId" ON "SocialStatusVisualizacoes" ("SocialStatusId", "UserId");
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                ALTER TABLE "SocialComentarios" DROP CONSTRAINT IF EXISTS "FK_SocialComentarios_PerfisSociais_PerfilSocialId";
                DROP TABLE IF EXISTS "SocialStatusVisualizacoes";
                DROP TABLE IF EXISTS "SocialStatus";
                DROP TABLE IF EXISTS "SocialPostsSalvos";
                ALTER TABLE "SocialComentarios" DROP COLUMN IF EXISTS "PerfilSocialId";
                ALTER TABLE "SocialPosts" DROP COLUMN IF EXISTS "Localizacao";
                ALTER TABLE "SocialPosts" DROP COLUMN IF EXISTS "TipoConteudo";
                """);
        }
    }
}
